services:

  fl-server:
    build: .
    container_name: fl-server
    command: python server.py
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - fl-network
    restart: on-failure

  fl-client0:
    build: .
    container_name: fl-client0
    command: python client.py 0
    environment:
      - SERVER_ADDRESS=fl-server:8080
    volumes:
      - ./data:/app/data
    networks:
      - fl-network
    depends_on:
      - fl-server
    restart: on-failure

  fl-client1:
    build: .
    container_name: fl-client1
    command: python client.py 1
    environment:
      - SERVER_ADDRESS=fl-server:8080
    volumes:
      - ./data:/app/data
    networks:
      - fl-network
    depends_on:
      - fl-server
    restart: on-failure

  fl-client2:
    build: .
    container_name: fl-client2
    command: python client.py 2
    environment:
      - SERVER_ADDRESS=fl-server:8080
    volumes:
      - ./data:/app/data
    networks:
      - fl-network
    depends_on:
      - fl-server
    restart: on-failure

  fl-ui:
    build: .
    container_name: fl-ui
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - fl-network
    restart: on-failure

networks:
  fl-network:
    driver: bridge